CREATE TABLE IF NOT EXISTS teste (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 

DROP TABLE IF EXISTS teste;

CREATE TABLE IF NOT EXISTS teste (
	cpf VARCHAR(50) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (cpf)
); 

INSERT INTO teste (cpf, nome, created_at)
VALUES ('42726879874', 'Arthur k', '2020-06-01 15:20:00' ) ON CONFLICT (cpf) DO NOTHING;

UPDATE teste SET nome = 'Bruno Lan' WHERE cpf = '42726879874';

SELECT * FROM teste;